config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  

  resources :docs
  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end

  root 'welcome#index'

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
    before_action :find_doc, only: [:show, :edit, :update, :destroy]
   
    def index
        @docs = Doc.where(user_id: current_user)
    end

    def show 
        
    end

    def new
        @doc = current_user.docs.build
    end

    def create
        @doc = current_user.docs.build(doc_params)

        if @doc.save
            redirect_to @doc
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @doc.update(doc_params)
            redirect_to @doc
        else
            render 'edit'
        end
    end

    def destroy
        @doc.destroy
        redirect_to docs_path
    end

    private
        def find_doc
            @doc = Doc.find(params[:id])
        end

        def doc_params
            params.require(:doc).permit(:title, :context)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
    = f.input :title
    = f.input :context, label:'Content'
    = f.button :submit

app/views/docs/edit.html.haml
.wrapper_with_padding
  %h1 Fix Doc !

  = render 'form'
  = link_to 'cancel', doc_path

app/views/docs/index.html.haml
.wrapper_with_padding
  #docs.clearfix
    - unless @docs.blank?
      - @docs.each do |doc|
        %a{ href: (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= time_ago_in_words(doc.created_at)
            %p.content= truncate(doc.context, length:50)

    - else
      %h2 Create Doc!
      %p Start Creating Document
      %button= link_to 'created doc', new_doc_path

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 Create Doc  
  = render 'form'

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.context)
    
    .buttons
      = link_to 'Fix Doc', edit_doc_path(@doc), class: 'button'
      = link_to 'Trash it', doc_path(@doc), method: :delete, data: { Confirm: "Are you sure ?"}, class: 'button'

app/views/layouts/application.html.haml
%html
  %head
    %title FileCabinet
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags
%body
  %header
    .header_inner
      = link_to 'FileCabinet', root_path, id:'logo'

      %nav
        - if user_signed_in?
          = link_to 'Create Doc', new_doc_path
          = link_to 'Sign out', destroy_user_session_path, method: :delete
        
        - else
          = link_to 'Log in', new_user_session_path

  %p.notice= notice
  %p.alert= alert
    
  = yield

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 File Cabinet
    %p Life is never flat
    %button= link_to 'Enter', new_user_registration_path

#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Organize
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec.

#bottom_cta
  .wrapper
    %h2 Go Ahead!
    %br
    %button= link_to 'Join Now', new_user_registration_path